import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { invoke } from '../transport';

export type StorageMode = 'local' | 'remote';

type StorageModePayload = {
  mode: 'Local';
} | {
  mode: 'Remote';
  url: string;
  api_key: string | null;
};

interface SettingsStore {
  apiId: string | null;
  apiHash: string | null;
  isConfigured: boolean;

  // Storage mode
  storageMode: StorageMode;
  backendUrl: string;
  // NOTE: API key is persisted to localStorage via zustand persist middleware.
  // This is acceptable for a desktop Tauri app (equivalent to storing in the app's data dir).
  backendApiKey: string;
  storageSwitching: boolean;
  storageError: string | null;
  folderLayout: 'horizontal' | 'vertical';
  chatDensity: 'normal' | 'compact' | 'very-compact';
  messageTextSize: 'small' | 'medium' | 'large';
  markdownMode: 'plain' | 'rendered';
  mergeMessages: boolean;
  interfaceScale: number;
  notificationsEnabled: boolean;
  notificationSound: boolean;
  messagePreview: boolean;
  // Calls are experimental: the VoIP transport has no real encryption yet,
  // so the whole feature is opt-in and hidden by default.
  experimentalCalls: boolean;

  // Local API server (desktop only): off by default; serves the vasya-server
  // router in-process on 127.0.0.1 for local AI agents / MCP clients.
  localApiEnabled: boolean;
  localApiPort: number;
  // Bearer token generated by the backend on first enable; persisted so MCP
  // client configs survive app restarts (regenerate to rotate).
  localApiToken: string | null;
  // Runtime status — excluded from persistence (see partialize below).
  localApiRunning: boolean;
  localApiBusy: boolean;
  localApiError: string | null;

  // Engine mode (desktop): 'embedded' (default, local grammers engine) or
  // 'remote' (external vasya-server over HttpTransport). Read at boot in
  // main.tsx — the transport factory can't read this store (circular import).
  transportMode: 'embedded' | 'remote';

  setApiCredentials: (apiId: string, apiHash: string) => void;
  markConfigured: () => void;
  clearApiCredentials: () => void;

  setStorageMode: (mode: StorageMode, url?: string, apiKey?: string) => Promise<void>;
  setFolderLayout: (layout: 'horizontal' | 'vertical') => void;
  setChatDensity: (density: 'normal' | 'compact' | 'very-compact') => void;
  setMessageTextSize: (size: 'small' | 'medium' | 'large') => void;
  setMarkdownMode: (mode: 'plain' | 'rendered') => void;
  setMergeMessages: (merge: boolean) => void;
  setInterfaceScale: (scale: number) => void;
  setNotificationsEnabled: (enabled: boolean) => void;
  setNotificationSound: (enabled: boolean) => void;
  setMessagePreview: (enabled: boolean) => void;
  setExperimentalCalls: (enabled: boolean) => void;

  setTransportModePreference: (mode: 'embedded' | 'remote') => void;
  /**
   * Switch engine mode and restart the app (desktop): persists the
   * preference, swaps the per-mode account list snapshots in localStorage,
   * flips the Rust-side marker, relaunches. Rolls back and rethrows when a
   * native call fails.
   */
  switchTransportMode: (mode: 'embedded' | 'remote') => Promise<void>;

  setLocalApiPort: (port: number) => void;
  /** Start (or restart) the local API server; regenerateToken rotates the bearer token. */
  startLocalApi: (regenerateToken?: boolean) => Promise<void>;
  stopLocalApi: () => Promise<void>;
  /** App start: re-arm the server if the persisted toggle is on. */
  syncLocalApi: () => Promise<void>;
}

interface LocalApiStatus {
  running: boolean;
  port: number | null;
  token: string | null;
}

export const useSettingsStore = create<SettingsStore>()(
  persist(
    (set, get) => ({
      apiId: null,
      apiHash: null,
      isConfigured: false,

      storageMode: 'local' as StorageMode,
      backendUrl: 'http://localhost:3000',
      backendApiKey: '',
      storageSwitching: false,
      storageError: null,
      folderLayout: 'horizontal',
      chatDensity: 'normal',
      messageTextSize: 'medium' as const,
      markdownMode: 'plain' as const,
      mergeMessages: true,
      interfaceScale: 100,
      notificationsEnabled: true,
      notificationSound: true,
      messagePreview: true,
      experimentalCalls: false,

      localApiEnabled: false,
      localApiPort: 8642,
      localApiToken: null,
      localApiRunning: false,
      localApiBusy: false,
      localApiError: null,

      transportMode: 'embedded' as const,

      setApiCredentials: (apiId, apiHash) => set({
        apiId,
        apiHash,
        isConfigured: true,
      }),

      markConfigured: () => set({
        isConfigured: true,
      }),

      clearApiCredentials: () => set({
        apiId: null,
        apiHash: null,
        isConfigured: false,
      }),

      setStorageMode: async (mode, url, apiKey) => {
        set({ storageSwitching: true, storageError: null });
        try {
          const payload: StorageModePayload = mode === 'local'
            ? { mode: 'Local' }
            : { mode: 'Remote', url: url || get().backendUrl, api_key: apiKey || get().backendApiKey || null };

          await invoke('set_storage_mode', { mode: payload });

          set({
            storageMode: mode,
            backendUrl: url || get().backendUrl,
            backendApiKey: apiKey !== undefined ? apiKey : get().backendApiKey,
            storageSwitching: false,
          });
        } catch (err) {
          set({
            storageSwitching: false,
            storageError: String(err),
          });
          throw err;
        }
      },
      setFolderLayout: (layout) => set({ folderLayout: layout }),
      setChatDensity: (density) => set({ chatDensity: density }),
      setMessageTextSize: (size) => set({ messageTextSize: size }),
      setMarkdownMode: (mode) => set({ markdownMode: mode }),
      setMergeMessages: (merge) => set({ mergeMessages: merge }),
      setInterfaceScale: (scale) => set({ interfaceScale: scale }),
      setNotificationsEnabled: (enabled) => set({ notificationsEnabled: enabled }),
      setNotificationSound: (enabled) => set({ notificationSound: enabled }),
      setMessagePreview: (enabled) => set({ messagePreview: enabled }),
      setExperimentalCalls: (enabled) => set({ experimentalCalls: enabled }),

      setTransportModePreference: (mode) => set({ transportMode: mode }),

      switchTransportMode: async (mode) => {
        const current = get().transportMode;
        if (mode === current) return;
        const ACCOUNTS_KEY = 'telegram-accounts';
        const snapshot = localStorage.getItem(ACCOUNTS_KEY);
        try {
          set({ transportMode: mode });
          if (snapshot !== null) localStorage.setItem(`${ACCOUNTS_KEY}:${current}`, snapshot);
          const saved = localStorage.getItem(`${ACCOUNTS_KEY}:${mode}`);
          if (saved !== null) localStorage.setItem(ACCOUNTS_KEY, saved);
          else localStorage.removeItem(ACCOUNTS_KEY);
          await invoke('set_remote_mode', { enabled: mode === 'remote' });
          await invoke('restart_app');
        } catch (err) {
          set({ transportMode: current });
          if (snapshot !== null) localStorage.setItem(ACCOUNTS_KEY, snapshot);
          else localStorage.removeItem(ACCOUNTS_KEY);
          throw err;
        }
      },

      setLocalApiPort: (port) => set({ localApiPort: port }),

      startLocalApi: async (regenerateToken = false) => {
        set({ localApiBusy: true, localApiError: null });
        try {
          const status = await invoke<LocalApiStatus>('start_local_api', {
            port: get().localApiPort,
            token: regenerateToken ? null : get().localApiToken,
          });
          set({
            localApiEnabled: true,
            localApiRunning: true,
            localApiToken: status.token ?? get().localApiToken,
            localApiPort: status.port ?? get().localApiPort,
            localApiBusy: false,
          });
        } catch (err) {
          set({
            // Failed to start (e.g. port in use): drop the toggle so the UI
            // doesn't claim a server that isn't there.
            localApiEnabled: false,
            localApiRunning: false,
            localApiBusy: false,
            localApiError: String(err),
          });
        }
      },

      stopLocalApi: async () => {
        set({ localApiBusy: true, localApiError: null });
        try {
          await invoke('stop_local_api');
          set({ localApiEnabled: false, localApiRunning: false, localApiBusy: false });
        } catch (err) {
          set({ localApiBusy: false, localApiError: String(err) });
        }
      },

      syncLocalApi: async () => {
        if (!get().localApiEnabled) return;
        try {
          const status = await invoke<LocalApiStatus>('local_api_status');
          if (status.running) {
            set({
              localApiRunning: true,
              localApiToken: status.token ?? get().localApiToken,
              localApiPort: status.port ?? get().localApiPort,
            });
            return;
          }
        } catch {
          // Backend without the command (e.g. web build) — leave it off.
          return;
        }
        await get().startLocalApi();
      },
    }),
    {
      name: 'telegram-settings',
      // Runtime status must not survive a restart (a persisted "running"
      // would make syncLocalApi skip re-arming the server).
      partialize: (state) =>
        Object.fromEntries(
          Object.entries(state).filter(
            ([key]) => !['localApiRunning', 'localApiBusy', 'localApiError'].includes(key)
          )
        ) as SettingsStore,
    }
  )
);
